### ISSUE TITLE
Fix support check for Inverse Gaussian

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#106]
This should fail, since the [support for the Inverse Gaussian](https://en.wikipedia.org/wiki/Inverse_Gaussian_distribution) is $(0, \infty)$.

```r
validateSupport.trunc_invgauss(n = 0, NULL)
```

It does indeed fail on `rmutil::prinvgauss()`

```r
rmutil::pinvgauss(q = 0, m = 1, s = 2)
```

The former does not fail because `judgeSupportLimits()` doesn't distinguish between $< 0$ and $\le 0$ in this particular case.

**Comment by rho62** [comment]
I think it’s best that it actually does fail, in the same way that we expect an error message if issue log(0)
/René

Fra: Waldir Leoncio ***@***.***>
Svar til: ocbe-uio/TruncExpFam ***@***.***>
Dato: fredag 1. mars 2024 kl. 17:34
Til: ocbe-uio/TruncExpFam ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [ocbe-uio/TruncExpFam] Fix support check for Inverse Gaussian (Issue #106)


This should fail, since the support for the Inverse Gaussian<https://en.wikipedia.org/wiki/Inverse_Gaussian_distribution> is $(0, \Inf)$.

validateSupport.trunc_invgauss(n = 0, NULL)

It does indeed fail on rmutil::prinvgauss()

rmutil::pinvgauss(q = 0, m = 1, s = 2)

The former does not fail because judgeSupportLimits() doesn't distinguish between $&lt; 0$ and $\le 0$ in this particular case.
