### ISSUE TITLE
Test `cumDens()` further

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#113]
This function is part of the `rtrunc_direct()` function:

https://github.com/ocbe-uio/TruncExpFam/blob/a0057743c341151caaa8bb1a168f0a8c4708401b/R/rtrunc_direct.R#L198-L207

I'm not sure if testing `x` against $\{-\infty, 0, 1, \infty\}$ is appropriate, or if it should be tested against the support of the distribution. Maybe it doesn't matter in the end, since `x` in practice is always one of the truncation limits (`a` or `b`), but it's good to think about this a little bit and tinker.

Some notes from before:

- x can be 0 and still have F(x) > 0
- x can be 1 and still have F(x) < 1

**Comment by rho62** [comment]
Hi Waldir

If we have a distribution ‘dist’ truncated to (a; b) (which could be the full domain, doubly truncated or one-sided)

Then
pdist(x)=0 for x < a and pdist(x)=1 for x>=b
qdist(0)=a and qdist(1)=b
ddist(x)=0 for x<a OR x>b

In other words: use the domain of the truncated distribution, which is (a,b)
Hope this answers the question

/René


Fra: Waldir Leoncio ***@***.***>
Svar til: ocbe-uio/TruncExpFam ***@***.***>
Dato: onsdag 28. august 2024 kl. 09:41
Til: ocbe-uio/TruncExpFam ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [ocbe-uio/TruncExpFam] Test `cumDens()` further (Issue #113)


This function is part of the rtrunc_direct() function:

https://github.com/ocbe-uio/TruncExpFam/blob/a0057743c341151caaa8bb1a168f0a8c4708401b/R/rtrunc_direct.R#L198-L207

I'm not sure if testing x against ${-\infty, 0, 1, \infty}$ is appropriate, or if it should be tested against the support of the distribution. Maybe it doesn't matter in the end, since x in practice is always one of the truncation limits (a or b), but it's good to think about this a little bit and tinker.

Some notes from before:

  *   x can be 0 and still have F(x) > 0
  *   x can be 1 and still have F(x) < 1

**Comment by wleoncio** [comment]
Thank you for the quick reply, René! I'll write some tests about this to make sure the function is performing correctly.
