### ISSUE TITLE
Implement "invisible" distributions in rtrunc

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#30]

**Comment by wleoncio** [comment]
The list of distributions which are coded but still need to be included in rtrunc and its subfunctions (`genRtruncClass()` and `validateDomain()`) has expanded since the original post, so I am going to list them again to keep track (and edit the issue title accordingly).

- [x] Beta
- [x] Binomial
- [x] Chisq
- [x] Continuous Bernoulli
- [x] Exponential
- [x] Gamma
- [x] Inverse Gamma
- [x] Inverse Gaussian
- [x] Log-normal
- [x] Negative Binomial
- [x] Normal
- [x] Poisson

**Comment by wleoncio** [comment]
Addition to `validateDomain()` requires PR #39 to be merged into develop. Waiting...

**Comment by wleoncio** [comment]
The unchecked functions need their rtrunc method to be coded. They only have dtrunc methods so far.

Coding follows the same format from the other functions: use the stats analog function and, trimming conditions and S3 class.

**Comment by wleoncio** [comment]
Next step:

- [ ] Add structure for all remaining rtrunc methods with `stop()` interruption so that all the subsequent functions (e.g. aliases) are in place.
