### ISSUE TITLE
Naming of functions

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#47]
use ". " rather than "_" in function names:  xxx.trunc_normal -> xxx.trunc.normal
And avoid using "trunc" twice as in "dtrunc.trunc_normal" Should be "dtrunc.normal"
And similar for all distributions.
Reluctant to do this, as I'm uncertain about the repercussions for other parts

**Comment by wleoncio** [comment]
I'm not sure about the consequences of using `.` inside method names, but at least visually a name like `xxx.trunc.normal` it creates a problem of knowing which is the generic (say, `xxx`) and which is the method (`trunc.normal`). To be safe, I'd recommend keeping `.` out of function names unless it's a separator between a generic function such as `dtrunc` and its methods (e.g. `trunc_normal`).

S3 methods are named after the class of the object that is being passed to them, so renaming methods like `trunc_normal` to `normal` is possible, but requires renaming the class of its input. This might create confusion because objects created by `rtrunc` would not have the word "trunc" in their class name. For instance, in the code below:

![image](https://user-images.githubusercontent.com/8234768/121846915-0dbe8200-cce8-11eb-84f6-1cfe957cca6a.png)

`class(x)` would be `normal` if the proposed changes were applied. Af far as I know, that doesn't generate any conflicts with objects from the `stats` package, but it is an uninformative name because it lacks information about the truncation.

One alternative solution would be to remove the `_` in the class names and name them as `truncnormal`, for instance. Another would be for rtrunc output objects to have two classes, so `class(x)` would print `"trunc" "normal"`, though that will probably break some things elsewhere.

I'll write again if I can think of another solution.

**Comment by wleoncio** [comment]
Oooh, I just remembered. If this issue is specific for `dtrunc`, we can do the same we did for `rtrunc` (see issue #43) and create aliases so the user runs `dtruncnorm` (which is more in line with the `stats` nomenclature) instead of `dtrunc.trunc_normal` (which they technically should be discouraged of using anyway, in favor of the generic `dtrunc`).
