### ISSUE TITLE
init.parms

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#87]
Unclear what the purpose is for this function. The help files says that it gives the empirical parameter estimates.
Perhaps "emp.parms" is a more suitable name for this function.
The help file says that the argument for init.parms is an output from rtrunc, meaning that it is of type "trunc_XXXX". If there should be a function init.parms with taking an object of class "trunc_XXXX" as argument, I suggest that it should be the parmeters that the rtrunc was called with:

Ex:
NOW: 
x <- rtrunc(n = 100, mean = 2, sd=1.5)
> class(init.parms(x))
[1] "trunc_normal"
> init.parms(x)
[1] 1.960420 1.347519

I Suggest that init.parm(x) should return mean=2, sd=2 (and perhaps n=100)

Uncertain if this change affects other parts

**Comment by wleoncio** [comment]
`init.parms()` is used in `mlEstimationTruncDist()` to create `eta.j` based on the sample statistics (as you showed on your post), so altering the behavior of the former would directly (and adversely, as I understand) impact the latter. Two alternatives I see here are either having an argument on `init.parms()` to show the underlying parameters of the sample distribution or have `emp.parms()` as a separate function.

Or perhaps the problem is simply the title of `init.parms()`, which should not contain the word "estimates". Maybe it should be "empirical parameter statistics" instead?

BTW, just remembering that `print(x, details=TRUE)` will print the original distribution parameters (among other things). Maybe `emp.parms()` could be a wrapper around that to just show the elements you mentioned (parameters + sample size)?
